db_user: 'yauhen'
db_password: '123456'
email_sender: 'fcbb99mailer@gmail.com'
password_sender: 'K0000000k'
default_url_host: 'localhost:3000'
google_api_id: '572142732005-c7qdd3m50bu4mvtopb4d1as0th2pg348.apps.googleusercontent.com'
google_api_key: 'xIJTn6Qxl8bxokvvACqUWS-B'
